name: CI - Notificación Automática Alvely Bencosme 2024-1041

on:
  push:
    branches: ["main"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta CI personalizada - Alvely Bencosme
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
            -H "Title: Integración Continua Ejecutada - Alvely Bencosme Ramos" \
            -H "Priority: 5" \
            -H "Tags: devops,itla,alvely,ci" \
            -H "Content-Type: application/json" \
            -d '{
              "estudiante": "Alvely Bencosme Ramos",
              "matricula": "2024-1041",
              "repositorio": "${{ github.repository }}",
              "usuario_github": "${{ github.actor }}",
              "mensaje_commit": "${{ github.event.head_commit.message }}",
              "rama": "${{ github.ref_name }}",
              "resultado": "Workflow ejecutado exitosamente"
            }'
